### ISSUE TITLE
TypeError: Cannot read property 'assignChannel' of undefined

### ISSUE THREAD

**Issue by sam2b** [Loghorn/ant-plus#15]
Hello.  I'm unable to work around this error.  Please advise.  Thanks.

pi@raspberrypi:~/ant-cycling-power $ sudo node test.js
/home/pi/ant-cycling-power/power-meter.js:15
    stick.write(Ant.Messages.assignChannel(channel, 'transmit'));
                             ^

TypeError: Cannot read property 'assignChannel' of undefined
    at GarminStick2.<anonymous> (/home/pi/ant-cycling-power/power-meter.js:15:30)
    at emitOne (events.js:116:13)
    at GarminStick2.emit (events.js:211:7)
    at GarminStick2.USBDriver.read (/home/pi/.nvm/versions/node/v8.11.1/lib/node_modules/ant-plus/build/ant.js:527:18)
    at InEndpoint.<anonymous> (/home/pi/.nvm/versions/node/v8.11.1/lib/node_modules/ant-plus/build/ant.js:374:23)
    at emitOne (events.js:116:13)
    at InEndpoint.emit (events.js:211:7)
    at Transfer.transferDone (/home/pi/.nvm/versions/node/v8.11.1/lib/node_modules/ant-plus/node_modules/usb/usb.js:328:9)

**Comment by sam2b** [comment]
This error is because of a bug in ant-plus.js missing this line in the module.exports = { } block:
Messages: Ant.Messages,

**Comment by Loghorn** [comment]
Can you please provide the code to reproduce the issue?
Thank you

**Comment by sam2b** [comment]
Sure, see file here: https://github.com/olympum/ant-cycling-power/blob/master/power-meter.js
`  stick.on('startup', function () {`
`    console.log('startup');`
`    console.log('Max channels:', stick.maxChannels);`
`    var deviceId = 0xBEEF;`
`    stick.write(Ant.Messages.assignChannel(channel, 'transmit'));`
`    stick.write(Ant.Messages.setDevice(channel, deviceId, 11, 1));`
`    stick.write(Ant.Messages.setFrequency(channel, 57));`
`    stick.write(Ant.Messages.setPeriod(channel, 8182));`
`    stick.write(Ant.Messages.openChannel(channel));`
`    console.log('cycling power meter initialized');`
`  });`
`...`

**Comment by sam2b** [comment]
Regardless of the project, is it improper to write Ant.Messages.* to the stick?  If not, what & where is your intended use of Ant.Messages, because the missing export was the source of my issues.  Please advise.

**Comment by Loghorn** [comment]
Ant.Messages is meant to be used only by the library internal functions (and this is the reason it's not exported)
