### ISSUE TITLE
ANT+ USB stick not found! - Raspberry Pi

### ISSUE THREAD

**Issue by mikeherriman** [Loghorn/ant-plus#37]
pi@raspberrypi:~/ant-plus/sample $ lsusb
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 008: ID 0e8f:2517 GreenAsia Inc.
Bus 001 Device 004: ID 1a86:e5e3 QinHeng Electronics
**Bus 001 Device 009: ID 0fcf:1008 Dynastream Innovations, Inc. ANTUSB2 Stick**
Bus 001 Device 002: ID 2109:3431 VIA Labs, Inc. Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

$ ls /dev/ttyUSB0
**/dev/ttyUSB0**

When I attempt to run my program I get the error:
ANT+ USB stick not found!
/home/pi/ant-plus/build/ant.js:522
        this.outEp.transfer(data, function (error) {
                   ^

TypeError: Cannot read property 'transfer' of undefined
    at GarminStick3.USBDriver.write (/home/pi/ant-plus/build/ant.js:522:20)
    at StrideSpeedDistance.broadcast (/home/pi/ant-plus/sample/strideSpeedDistance/strideSpeedDistance.js:65:16)
    at a (/home/pi/ant-plus/sample/strideSpeedDistance/start.js:93:9)
    at Object.<anonymous> (/home/pi/ant-plus/sample/strideSpeedDistance/start.js:98:1)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47

any help will be greatly appreciated.
MIke

**Comment by robkiger** [comment]
There's at least two differing ANT+ stick ID codes - I have an old Garmin ANT stick (the long one, not the short stubby type) so had to change the coding in at least one of the files as it appears to reference the stubby one. Otherwise you do get the can't find stick error.

For what it's worth, though I got it all working in the end (the debug output showing the treadmill speed correctly), the ANT transmission of this failed to work - Zwift would pick up and pair to the device ID in the pairing screen okay, but 99% of the time the speed remained at zero. Very rarely Zwift would pick up the speed for about a second, then lose it again. I tried everything I could think of, moving the ANT sticks closer together to rule out interference/loss of signal, but the issue remained. I gave up in the end, which is a shame as it would have been great if I could have got it to work.

**Comment by mikeherriman** [comment]
Hey Rob,
I was able to get my USB Stick found by editing the GarminStick3 to GarminStick2.

It looks like I am in the same boat as you.....Zwift pairs and connects AOK, but speed at 0.....once in a while Zwift will pick it up, but primarily stuck at 0.

I will continue to test and troubleshoot.  If I get it going, I will post back.
