### ISSUE TITLE
LIBUSB_ERROR_BUSY

### ISSUE THREAD

**Issue by r3trosteve** [Loghorn/ant-plus#6]
This is a great library, was very easy to get started with after trying the python equivalent for raspberry pi.

After initially running just fine though and a few restarts, I then got the following error:

LIBUSB_ERROR_BUSY

```
pi@raspberrypi:~/ant-plus/sample $ node cadence-sensor.js 
/home/pi/ant-plus/node_modules/usb/usb.js:168
    this.device.__claimInterface(this.id)
                ^

Error: LIBUSB_ERROR_BUSY
    at Error (native)
    at Interface.claim (/home/pi/ant-plus/node_modules/usb/usb.js:168:14)
    at GarminStick2.USBDriver.open (/home/pi/ant-plus/build/ant.js:287:20)
    at Object.<anonymous> (/home/pi/ant-plus/sample/cadence-sensor.js:41:12)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
```

Any idea how I can ensure whatever is claiming it is detached from the interface?

**Comment by r3trosteve** [comment]
Just realised that I think it may have been due to killing the node script by hitting `ctrl + z`, whereas using `ctrl + x` worked fine on multiple occasions to that point.

Wondering if there's some open process running that I need to close gracefully somehow...

**Comment by Loghorn** [comment]
Sorry for taking so long to reply...
To be sure to gracefully close the serial, be sure to call the close method of the stick object
